/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTalksRouteImport } from './routes/_app.talks'
import { Route as AppInstructorsRouteImport } from './routes/_app.instructors'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTalksRoute = AppTalksRouteImport.update({
  id: '/talks',
  path: '/talks',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsRoute = AppInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructors': typeof AppInstructorsRoute
  '/talks': typeof AppTalksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructors': typeof AppInstructorsRoute
  '/talks': typeof AppTalksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/instructors': typeof AppInstructorsRoute
  '/_app/talks': typeof AppTalksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/instructors' | '/talks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/instructors' | '/talks'
  id: '__root__' | '/' | '/_app' | '/_app/instructors' | '/_app/talks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/talks': {
      id: '/_app/talks'
      path: '/talks'
      fullPath: '/talks'
      preLoaderRoute: typeof AppTalksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instructors': {
      id: '/_app/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AppInstructorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInstructorsRoute: typeof AppInstructorsRoute
  AppTalksRoute: typeof AppTalksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInstructorsRoute: AppInstructorsRoute,
  AppTalksRoute: AppTalksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
